# fly.toml app configuration file generated for tasklist-delicate-forest-5871 on 2025-04-04T10:56:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tasklist-delicate-forest-5871'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_NAME = 'Laravel'
  APP_URL = 'https://delicate-forest-5871.fly.dev/'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'postgres'
  DB_HOST = 'aws-0-ap-northeast-1.pooler.supabase.com'
  DB_PORT = '6543'
  DB_USERNAME = 'postgres.imykjjftnwnyvjriwxmj'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'